import asyncio
import logging
from app.infrastructure.queue.async_queue import EventQueue
from app.application.use_cases.create_invoice import CreateInvoice
from app.domain.repositories.invoice_repository import InvoiceRepository
from app.domain.services.external_metadata_service import ExternalMetadataService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class EventProcessor:
    """
    The EventProcessor class is a worker that processes events from the event queue.
    It consumes change events generated by the MongoChangeStream and triggers the business logic to create invoices.
    """

    def __init__(
        self, 
        event_queue: EventQueue, 
        invoice_repository: InvoiceRepository,
        external_metadata_service: ExternalMetadataService
    ):
        """
        Initialize the EventProcessor.

        Args:
            event_queue (EventQueue): The queue where events are stored for processing.
            invoice_repository (InvoiceRepository): The repository that the CreateInvoice use case will use.
            external_metadata_service (ExternalMetadataService): The external service used to fetch enrichment metadata.
        """
        self.event_queue = event_queue
        # We inject both dependencies into the use case.
        self.create_invoice_use_case = CreateInvoice(invoice_repository, external_metadata_service)

    async def process_events(self):
        """
        Continuously process events from the event queue.
        """
        while True:
            event = await self.event_queue.get()  # Wait for the next event
            if event:
                try:
                    logger.info(f"Processing event: {event}")

                    # Extract order data
                    order_data = event.get("fullDocument")
                    if not order_data or "_id" not in order_data:
                        logger.error("Malformed event data: %s", event)
                    else:
                        order_id = order_data["_id"]
                        logger.info(f"Attempting to save invoice for order ID: {order_id}")
                        invoice_id = await self.create_invoice_use_case.execute(order_data)
                        logger.info(f"Successfully created invoice {invoice_id} for order ID: {order_id}")
                except Exception as e:
                    logger.error("Error while processing event: %s", e)

            self.event_queue.task_done()  # Mark the event as processed
