version: '3.9'

services:
  invoice-ms:
    build:
      context: ./services/invoice-ms
    container_name: invoice-ms
    env_file:
      - ./services/invoice-ms/.env
    ports:
      - "8000:8000"
    networks:
      - backend-net

  recommendation-ms:
    build:
      context: ./services/recommendation-ms
    container_name: recommendation-ms
    env_file:
      - ./services/recommendation-ms/.env
    networks:
      - backend-net

networks:
  backend-net:
