version: '3'
services:
  invoice-ms:
    build:
      context: ./services/invoice-ms  # Ruta al microservicio de invoice-ms
    ports:
      - "8000:8000"
    env_file:
      - ./services/invoice-ms/.env.local
    networks:
      - app-network

  # recommendation-ms:
  #   build:
  #     context: ./services/recommendation-ms  # Ruta al microservicio de recommendation-ms
  #   ports:
  #     - "8001:8000"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge