[tool.poetry]
name = "recommendation-ms"
version = "0.1.0"
description = "Recommendation Microservice for generating personalized suggestions based on purchases"
authors = ["Florencia Arin <florencia.arin@mongodb.com>"]
readme = "README.md"

# Include the app/ folder as the main package
packages = [{ include = "app" }]

[tool.poetry.dependencies]
# Python version compatibility
python = ">=3.10,<3.11"

# MongoDB drivers
pymongo = "^4.10.1"               # Sync MongoDB client (used by some libraries)
motor = "^3.7.0"                  # Async MongoDB client

# Environment and settings management
python-dotenv = "^1.0.1"          # Loads variables from .env
pydantic = ">=2.7,<3.0"           # Data validation and parsing
pydantic-settings = "^2.8.1"      # Pydantic-based environment config

# HTTP client for calling external APIs (if needed)
httpx = "^0.28.1"                 # Async HTTP requests

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
