from datetime import datetime
from typing import List, Dict, Optional
from bson import ObjectId

class Invoice:
    """
    Domain entity representing an invoice.
    Designed to be framework-agnostic and independent of infrastructure.
    """

    def __init__(
        self,
        order_id: str,
        user_id: str,
        items: List[Dict],
        created_at: Optional[datetime] = None,
        metadata: Optional[Dict] = None,
        recommendations: Optional[List[Dict]] = None,
        status: str = "pending",  # Default status is 'pending'
        _id: Optional[ObjectId] = None
    ):
        """
        Initialize an Invoice entity.

        Args:
            order_id (str): ID of the order this invoice is based on.
            user_id (str): ID of the user associated with the invoice.
            items (List[Dict]): List of items included in the invoice.
            created_at (datetime, optional): Timestamp of invoice creation. Defaults to now.
            metadata (Dict, optional): Additional data from external systems.
            recommendations (List[Dict], optional): Product suggestions.
            status (str): The status of the invoice (e.g., 'pending', 'paid'). Defaults to 'pending'.
            _id (ObjectId, optional): MongoDB's autogenerated ObjectId (used as invoice ID).
        """
        self._id = _id
        self.order_id = order_id
        self.user_id = user_id
        self.items = items
        self.created_at = created_at or datetime.utcnow()
        self.metadata = metadata or {}
        self.recommendations = recommendations or []
        self.status = status  # Set the status
        self.validate()  # Validate invoice data

    def validate(self):
        """Ensure that the required fields are valid."""
        if not self.order_id or not self.user_id:
            raise ValueError("Order ID and User ID are required")

    def calculate_total(self) -> float:
        """Calculate the total amount based on the items."""
        return sum(item['price']['amount'] for item in self.items)

    def enrich(self, external_data: Dict):
        """
        Enrich the invoice with external metadata (e.g., fraud check, loyalty data).
        """
        self.metadata.update(external_data)

    def to_dict(self) -> Dict:
        """
        Convert the Invoice entity to a dictionary for MongoDB storage.
        """
        invoice_dict = {
            "orderId": self.order_id,
            "userId": self.user_id,
            "items": self.items,
            "createdAt": self.created_at.isoformat(),
            "metadata": self.metadata,
            "recommendations": self.recommendations,
            "status": self.status,  # Include the status in the dictionary
            "totalAmount": self.calculate_total()  # Include total amount in the dict
        }

        if self._id:
            invoice_dict["_id"] = self._id
            invoice_dict["invoiceId"] = str(self._id)

        return invoice_dict

    @staticmethod
    def from_order(order: Dict, _id: Optional[ObjectId] = None):
        """
        Create an Invoice entity from an order dictionary.
        """
        return Invoice(
            order_id=order["_id"],
            user_id=order["user"],
            items=order["products"],
            _id=_id
        )
